name: .NET Framework CI Workflow

# Trigger events
on:
  push:
    branches:
      - main
      - '**'  # This will trigger for any branch
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # This runs daily at midnight

jobs:
  build:
    runs-on: windows-latest  # Running on Windows for .NET Framework

    # Condition at job level: Only run this job for pushes to the 'main' branch
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Framework
        uses: actions/setup-dotnet@v2
        with:
          sdk: '3.1.x'  # Adjust to your version of .NET Framework, if needed

      # Navigate to the project folder (if your project is in a subfolder)
      - name: Change directory to MyDotNetApp
        run: cd MyDotNetApp

      - name: Restore dependencies
        run: dotnet restore MyDotNetApp/MyDotNetApp.csproj  # Specify path to .csproj or .sln file

      - name: Build project
        run: dotnet build MyDotNetApp/MyDotNetApp.csproj --configuration Release  # Specify path to .csproj or .sln file

      - name: Run tests
        run: dotnet test MyDotNetApp/MyDotNetApp.csproj --configuration Release  # Specify path to .csproj or .sln file

      - name: Publish project (if on main branch)
        if: github.ref == 'refs/heads/main'  # Condition at step level
        run: dotnet publish MyDotNetApp/MyDotNetApp.csproj --configuration Release --output ./publish  # Specify path to .csproj or .sln file

  
